spring:
  datasource:
    url: jdbc:h2:file:/data/demo
    username: sa
    password: password
    driverClassName: org.h2.Driver
  h2:
    console.enabled: true
  liquibase:
    enabled: true
    changeLog: classpath:db/changelog/dbchangelog.xml
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
    #  ddl-auto: create-drop
    #defer-datasource-initialization: true
